In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import time
start = time.time()
import pandas as pd
import numpy as np

from joblib import  dump, load
Training_data=load('/content/drive/My Drive/train_data_model_building.joblib')


from keras.models import Sequential
from keras.layers import Dense,Input
neural_network = Sequential()


neural_network.add(Dense(32, input_dim=21, activation = 'relu',
                         kernel_initializer = 'RandomUniform', bias_initializer = 'zeros'))

neural_network.add(Dense(10, activation = 'relu', kernel_initializer = 'zeros',
                         bias_initializer = 'RandomUniform'))


neural_network.add(Dense(4, activation = 'relu', kernel_initializer = 'zeros',
                         bias_initializer = 'RandomUniform'))

neural_network.add(Dense(1, activation = 'linear', kernel_initializer = 'zeros',
                         bias_initializer = 'RandomUniform'))
neural_network.summary()

from keras.optimizers import Adam

customized_optimizer = Adam(lr = 0.001)

neural_network.compile(optimizer=customized_optimizer,
              loss='mean_squared_error',
              metrics=['mae'])

training_history = neural_network.fit(Training_data.copy().drop(['yield'],axis=1), Training_data['yield'], epochs=50, batch_size=1000000, validation_split=0.2)

done = time.time()
elapsed = done - start
print(elapsed)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 32)                704
_________________________________________________________________
dense_6 (Dense)              (None, 10)                330
_________________________________________________________________
dense_7 (Dense)              (None, 4)                 44
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 5
=================================================================
Total params: 1,083
Trainable params: 1,083
Non-trainable params: 0
_________________________________________________________________
Train on 15582493 samples, validate on 3895624 samples
Epoch 1/50
15582493/15582493 [==============================] - 190s 12us/step - loss: 190376.3577 - mean_absolute_error: 220.3742 - val_loss: 188042.3610 - val_mean_absolute_error: 212.0540
Epoch 2/50
15582493/15582493 [==============================] - 191s 12us/step - loss: 138029.6706 - mean_absolute_error: 181.5079 - val_loss: 132339.2031 - val_mean_absolute_error: 212.1555
Epoch 3/50
15582493/15582493 [==============================] - 189s 12us/step - loss: 109391.7413 - mean_absolute_error: 161.3983 - val_loss: 116829.2213 - val_mean_absolute_error: 159.0703
Epoch 4/50
15582493/15582493 [==============================] - 188s 12us/step - loss: 105066.7743 - mean_absolute_error: 161.4982 - val_loss: 115465.0273 - val_mean_absolute_error: 156.1990
Epoch 5/50
15582493/15582493 [==============================] - 188s 12us/step - loss: 104007.6018 - mean_absolute_error: 155.8371 - val_loss: 114464.7523 - val_mean_absolute_error: 158.9297
Epoch 6/50
15582493/15582493 [==============================] - 187s 12us/step - loss: 103719.4029 - mean_absolute_error: 154.7536 - val_loss: 114285.7802 - val_mean_absolute_error: 159.7099
Epoch 7/50
15582493/15582493 [==============================] - 188s 12us/step - loss: 103623.6016 - mean_absolute_error: 154.5244 - val_loss: 114206.3987 - val_mean_absolute_error: 160.2363
Epoch 8/50
15582493/15582493 [==============================] - 188s 12us/step - loss: 103542.1042 - mean_absolute_error: 154.5891 - val_loss: 114153.8416 - val_mean_absolute_error: 160.6263
Epoch 9/50
15582493/15582493 [==============================] - 186s 12us/step - loss: 103461.6666 - mean_absolute_error: 154.6026 - val_loss: 114072.5027 - val_mean_absolute_error: 160.7203
Epoch 10/50
15582493/15582493 [==============================] - 187s 12us/step - loss: 103374.5937 - mean_absolute_error: 154.5955 - val_loss: 113960.3766 - val_mean_absolute_error: 160.6339
Epoch 11/50
15582493/15582493 [==============================] - 185s 12us/step - loss: 103217.4235 - mean_absolute_error: 155.3426 - val_loss: 113752.3331 - val_mean_absolute_error: 160.9202
Epoch 12/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 103015.8671 - mean_absolute_error: 155.1390 - val_loss: 113518.2490 - val_mean_absolute_error: 160.5521
Epoch 13/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 102827.9019 - mean_absolute_error: 154.8896 - val_loss: 113321.8349 - val_mean_absolute_error: 161.0417
Epoch 14/50
15582493/15582493 [==============================] - 183s 12us/step - loss: 102639.0298 - mean_absolute_error: 155.0440 - val_loss: 113108.9258 - val_mean_absolute_error: 160.6419
Epoch 15/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 102440.1797 - mean_absolute_error: 155.2295 - val_loss: 112898.5135 - val_mean_absolute_error: 161.2976
Epoch 16/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 102219.1073 - mean_absolute_error: 155.5376 - val_loss: 112668.7613 - val_mean_absolute_error: 161.5960
Epoch 17/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 101974.1553 - mean_absolute_error: 155.9123 - val_loss: 112429.6235 - val_mean_absolute_error: 161.4433
Epoch 18/50
15582493/15582493 [==============================] - 187s 12us/step - loss: 101727.3932 - mean_absolute_error: 155.5963 - val_loss: 112143.1740 - val_mean_absolute_error: 161.5590
Epoch 19/50
15582493/15582493 [==============================] - 188s 12us/step - loss: 101465.7659 - mean_absolute_error: 155.6964 - val_loss: 111871.5213 - val_mean_absolute_error: 161.7601
Epoch 20/50
15582493/15582493 [==============================] - 187s 12us/step - loss: 101177.9115 - mean_absolute_error: 155.8232 - val_loss: 111569.7218 - val_mean_absolute_error: 161.4831
Epoch 21/50
15582493/15582493 [==============================] - 185s 12us/step - loss: 100869.8603 - mean_absolute_error: 155.8724 - val_loss: 111272.6791 - val_mean_absolute_error: 161.6360
Epoch 22/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 100528.7060 - mean_absolute_error: 155.8263 - val_loss: 110903.2383 - val_mean_absolute_error: 161.6967
Epoch 23/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 100134.6812 - mean_absolute_error: 155.8277 - val_loss: 110510.3936 - val_mean_absolute_error: 162.2919
Epoch 24/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 99663.0087 - mean_absolute_error: 155.6871 - val_loss: 109982.5216 - val_mean_absolute_error: 161.8958
Epoch 25/50
15582493/15582493 [==============================] - 184s 12us/step - loss: 99082.3222 - mean_absolute_error: 155.7953 - val_loss: 109247.4639 - val_mean_absolute_error: 161.1083
Epoch 26/50
 9000000/15582493 [================>.............] - ETA: 1:15 - loss: 98568.5443 - mean_absolute_error: 156.0334

In [0]:
load('/content/drive/My Drive/new_test_data_fully_model_ready.joblib')

        ingredient_type  ...  farm_id_ingredient_target_encoding_weightage
0                     0  ...                                  6.576176e+05
1                     0  ...                                  1.278194e+05
2                     0  ...                                  2.069071e+06
3                     0  ...                                  7.025458e+04
4                     0  ...                                  1.571848e+05
...                 ...  ...                                           ...
999994                0  ...                                  2.785244e+06
999995                1  ...                                  4.533394e+05
999996                0  ...                                  2.416129e+06
999997                0  ...                                  3.079276e+06
999998                1  ...                                  1.371837e+05

[999999 rows x 21 columns]